### ISSUE TITLE
8.11.0: fails to compile with ocaml 4.08.1

### ISSUE THREAD

**Issue by treinen** [coq/coq#11495]
#### Description of the problem

Coq fails to compile on my amd64 machine, using ocaml 4.08.1-7 from debian:

````
File "plugins/ssr/ssrparser.mlg", line 2328, characters 55-68:
Error: This expression has type
         'a -> 'b -> Ssrmatching_plugin.Ssrmatching.rpattern -> Pp.t
       but an expression was expected of type Pp.t
make[3]: *** [Makefile.build:770: plugins/ssr/ssrparser.cmx] Error 2
````

#### Coq Version

8.11.0

**Comment by ppedrot** [comment]
I cannot reproduce on my amd64 machine, using OCaml 4.08.1+fp from opam and Coq tag V8.11.0. This does not look like an OCaml problem though, are you sure you are using the right sources? What setting are you using exactly?

**Comment by treinen** [comment]
I just tried he same on the V8.11.0 release tag and I don't get the compilation error either. So something must have gone wrong in the debianized source tree. Sorry for the noise.
