### PR TITLE
[ci] [docker] Update base Dune version.

### PR DESCRIPTION
**Pull request by ejgallego**
We'd like to use `(lang 1.1)` features.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by ejgallego** [comment]
Psss, OPAM is at it again:

```
[elpi: make] Command started
[ERROR] The compilation of elpi failed at "make".
[elpi: make uninstall] Command started
[elpi: make uninstall-bin] Command started

#=== ERROR while installing elpi.1.0.4 ========================================#
# opam-version         1.2.2
# os                   linux
# command              make
# path                 /root/.opamcache/4.02.3/build/elpi.1.0.4
# compiler             4.02.3
# exit-code            2
# env-file             /root/.opamcache/4.02.3/build/elpi.1.0.4/elpi-15-6db8db.env
# stdout-file          /root/.opamcache/4.02.3/build/elpi.1.0.4/elpi-15-6db8db.out
# stderr-file          /root/.opamcache/4.02.3/build/elpi.1.0.4/elpi-15-6db8db.err
### stdout ###
# OCAMLOPT  elpi_config.mli           -c
# OCAMLOPT  elpi_config.ml            -c
# OCAMLOPT trace_ppx                  -o
# Makefile:23: recipe for target 'trace_ppx' failed
### stderr ###
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /root/.opamcache/4.02.3/lib/ocaml, /root/.opamcache/4.02.3/lib/ocaml/compiler-libs
# File "trace_ppx.ml", line 21, characters 5-18:
# Error: Unbound module Ppx_tools_402
# make: *** [trace_ppx] Error 2
```
@gares, any clue what broke?

**Comment by gares** [comment]
The module belongs to ppx_tools_versioned. I've just tried and version 5.2.1 broken elpi, it works fine with 5.1 (so if you want to build the image now, fix the version)

**Comment by ejgallego** [comment]
> The module belongs to ppx_tools_versioned. I've just tried and version 5.2.1 broken elpi, it works fine with 5.1 (so if you want to build the image now, fix the version)

Thanks for the info. No rush on my part, I'll wait for you to fix elpi and we then bump all the versions in this PR.

**Comment by gares** [comment]
See ocaml/opam-archive#12535 for the elpi related fix

**Comment by ejgallego** [comment]
Updated, thanks @gares
