### ISSUE TITLE
Parser confused ("Error: Unbound constructor Check")

### ISSUE THREAD

**Issue by herbelin** [coq/coq#10103]
I observed the following parsing issue, though did not investigate further.
```
Require Import Ltac2.Ltac2.
Check True. (* ok *)
Theorem T : True. auto. Qed.
Fail Check True. (* Error: Unbound constructor Check *)
```
Idem, with `Search`, `Compute`, but not with `Locate`, `Print`, ... which are at the same level of parsing. On the other side, `Eval` gives `"illegal begin of vernac"`.

**Comment by jfehrle** [comment]
This works on 8.12, shall we close this issue?

```
The command has not failed!
True
     : Prop
```

**Comment by jfehrle** [comment]
@herbelin  This works on 8.12, shall we close the issue?

**Comment by ejgallego** [comment]
Sure, if it works it should be closed. Thanks for triaging this @jfehrle
