### PR TITLE
[Extraction] [Haskell] Add support for GHC >= 9

### LINKED ISSUE #14256: Haskell extraction is broken for ghc 9.0
```coq
Require Import Coq.extraction.ExtrHaskellBasic.
Extraction Language Haskell.
Definition foo (t : { T : Type & T }) := projT2 t.
Definition bar := foo (existT _ (nat:Type) 0).
Recursive Extraction bar.
(*
{-# OPTIONS_GHC -cpp -XMagicHash #-}
{- For Hugs, use the option -F"cpp -P -traditional" -}

module Main where

import qualified Prelude

#ifdef __GLASGOW_HASKELL__
import qualified GHC.Base
import qualified GHC.Prim
#else
-- HUGS
import qualified IOExts
#endif

#ifdef __GLASGOW_HASKELL__
unsafeCoerce :: a -> b
unsafeCoerce = GHC.Base.unsafeCoerce#
#else
-- HUGS
unsafeCoerce :: a -> b
unsafeCoerce = IOExts.unsafeCoerce
#endif

#ifdef __GLASGOW_HASKELL__
type Any = GHC.Prim.Any
#else
-- HUGS
type Any = ()
#endif

__ :: any
__ = Prelude.error "Logical or arity value used"

data Nat =
   O
 | S Nat

data SigT a p =
   ExistT a p

projT2 :: (SigT a1 a2) -> a2
projT2 x =
  case x of {
   ExistT _ h -> h}

foo :: (SigT () Any) -> Any
foo t =
  projT2 t

bar :: Nat
bar =
  unsafeCoerce foo (ExistT __ (unsafeCoerce O))

*)
```
This code does not compile with ghc 9.0.1, failing with 
```
Error:     Not in scope: ‘GHC.Base.unsafeCoerce#’
    Perhaps you meant ‘GHC.Base.unsafeChr’ (imported from GHC.Base)
    Module ‘GHC.Base’ does not export ‘unsafeCoerce#’.
   |
22 | unsafeCoerce = GHC.Base.unsafeCoerce#
   |                ^^^^^^^^^^^^^^^^^^^^^^
```

According to https://github.com/haskell/primitive/issues/258, we should be using `GHC.Exts.unsafeCoerce#`, but the diff at https://gitlab.haskell.org/ghc/ghc/commit/74ad75e87317196c600dfabc61aee1b87d95c214 suggests this is not backwards compatible.

Also, it seems extraction is already broken on earlier versions of Haskell, as I get
```
/tmp/foo.hs:26:12: error:
    Not in scope: type constructor or class ‘GHC.Prim.Any’
    Perhaps you meant ‘GHC.Prim.Int#’ (imported from GHC.Prim)
    Module ‘GHC.Prim’ does not export ‘Any’.
   |
26 | type Any = GHC.Prim.Any
   |            ^^^^^^^^^^^^
```
with 8.6.5.

cc, uh, @zeldovich ?  (I'm not sure who knows about Hakell extraction)

### PR DESCRIPTION
**Pull request by JasonGross**
**Kind:** bug fix

Fixes #14256

- [x] Added / updated test-suite (Is there a way to do this?)
- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified). (is there any documentation to update?)
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).
- [ ] Overlay pull requests (if this breaks 3rd party developments in CI, see
https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md for details)

### CODE REVIEW

**Comment by pi8027** [comment]
> Added / updated test-suite (Is there a way to do this?)

No.

> Corresponding documentation was added / updated (including any warning and error messages added / removed / modified). (is there any documentation to update?)

I don't think so.

If you have some time, please check my recent comment: https://github.com/coq/coq/issues/14256#issuecomment-848404561.

**Comment by silene** [comment]
The tests in `test-suite/output` using `Extraction Language Haskell` need to be updated. As for `unsafeCoerce` vs `unsafeCoerce#`, the current pull request is conservative, so the change can be delayed to another pull request.

**Comment by pi8027** [comment]
Sure. I will test this fix with GHC 8.01, 8.02, and 8.10.4 (but unfortunately Stack does not seem to support GHC 9 yet). If I don't see any issue, I will push a fix for the test-suite and merge.

**Comment by JasonGross** [comment]
@pi8027 Thanks for the update!  I've updated this PR a bit further, since as I discovered in https://github.com/coq/coq/issues/14256#issuecomment-844599983 the change to `Any` is not needed, and in fact we only need to update `unsafeCoerce`.  Hence I've reverted the change to Any, which was already addressed in https://github.com/coq/coq/pull/6023

**Comment by JasonGross** [comment]
(Sorry for being so belated in updating this)

**Review by pi8027 — APPROVED** [review]
I confirm it works at least with GHC 7.10.3, 8.0.1, 8.0.2, and 8.10.4.

**Comment by pi8027** [comment]
@JasonGross Thanks. Just to be sure, did you test the output with GHC 9? If so, I think this is ready to merge as soon as CI passes.

**Comment by JasonGross** [comment]
I did not, as I don't have easy access to it.  I am basing the change on the tags of https://github.com/ghc/ghc/commit/74ad75e87317196c600dfabc61aee1b87d95c214, which indicate that it first showed up in 9.0

**Comment by JasonGross** [comment]
But I have tested effectively the same change with GHC 9 on Fiat-Crypto CI using https://github.com/mit-plv/fiat-crypto/blob/master/src/haskell.sed, so unless I've made a typo, it works

**Comment by pi8027** [comment]
OK, that seems fine with me. Let's merge.

**Comment by pi8027** [comment]
@coqbot: merge now
