### ISSUE TITLE
Improve developer documentation for using Dune

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13601]
Several useful points that appear not to be covered in the doc mentioned in the discussion.

--------------
The original issue text was:

`pkg:opam` fails with this error in #13095.  I can't guess why.  Help appreciated.

```
# File "clib/stats.mli", line 2, characters 5-8:
# 2 | open Loc
#          ^^^
# Error: Unbound module Loc
```

**Comment by Zimmi48** [comment]
The Dune job is also failing, so the error actually comes from there, and not from `opam`. You probably need to extend the `(libraries ...)` list of dependencies of one of the Dune file.

**Comment by ejgallego** [comment]
Indeed incorrect build configuration

**Comment by jfehrle** [comment]
I was not suggesting this was a random failure.  I just don't know where to start.  I still only use makefiles locally because `doc_grammar`, which I use constantly, isn't fully supported in Dune.

We should have a description somewhere of what dune/makefile changes you need to make when you add new code files--this is a common thing developers do.  I'm not aware of any such writeup.  It could link to relevant parts of the dune documentation.

`build-system.dune` might mention that you install it with `opam` IIUC.  The following doesn't look right:

```
$ dune

Command 'dune' not found, but can be installed with:

sudo apt install whitedune
```

It doesn't help that Dune doesn't tell you what it was compiling when it ran into the error.  Is there any plan in Coq or elsewhere to automatically generate the code dependencies?  It seems rather primitive to have to identify the dependencies by hand.

Also I thought Dune was being used to compile everything in CI.  How do you tell which is which?

Is there a way to disable the check for extra files?  Otherwise I may need to create a new source tree--I have quite a few useful files in my source tree.  (It's a lousy message--it seems to report the one file at a time and then quits.  And the error message can't be found by search engine.)

```
- file present in source tree
- vernac/dune:1
Hint: rm -f vernac/vernac.a
```

**Comment by Zimmi48** [comment]
> I was not suggesting this was a random failure.

No one said it was random.

>We should have a description somewhere of what dune/makefile changes you need to make when you add new code files--this is a common thing developers do.

Agreed.

>It doesn't help that Dune doesn't tell you what it was compiling when it ran into the error.

Well, it does tell you. That's the first line of your quoted error.

>It seems rather primitive to have to identify the dependencies by hand.

It's not so hard though. `loc.mli` appears in `lib/`, so you would need to add `lib` to your dependencies in `clib/dune`. But actually, you cannot do this because this would introduce a circular dependency between `lib` and `clib`. The conclusion is that you should not open `Loc` in a file located in `clib`.

BTW, this conclusion makes complete sense: `clib` is for extensions of the OCaml standard library, not anything Coq-specific. If you introduce a file that depends on `Loc`, it is Coq-specific, so it should not be there. Move it to `lib`.

**Comment by ejgallego** [comment]
The question has been answered, questions related to improving dune documentation / usability should be handled separately IMO [a few of the questions are already answered pretty clearly on dev/doc IMO]

> We should have a description somewhere of what dune/makefile changes you need to make when you add new code files

we already do

> The following doesn't look right

That's a debian / ubuntu problem, hard for us to workaround

> How do you tell which CI job uses which?

Only jobs with `dune` in the name use dune, until we fully migrate.

> It doesn't help that Dune doesn't tell you what it was compiling when it ran into the error.

AFAICT it told you.

> Is there any plan in Coq or elsewhere to automatically generate the code dependencies? It seems rather primitive to have to identify the dependencies by hand.

That's precisely what we want to avoid as to enforce some degree of modularity. 

> Is there a way to disable the check for extra files?

Already documented in `dev/doc` readme.

**Comment by Zimmi48** [comment]
> Only jobs with `dune` in the name use dune, until we fully migrate.

The `pkg:opam` job too (it hasn't dune in the name IIRC)

**Comment by jfehrle** [comment]
Right, it's not in the name.  Same thing for `lint`.

> > Is there a way to disable the check for extra files?

> Already documented in `dev/doc` readme.

Where is it?  I looked at all the references to "dune" in the .md files.  The only thing I saw related to this is in `build-system.dune.md`, which says "Dune will get confused if it finds leftovers of in-tree compilation, so please be sure your tree is clean from objects files generated by the make-based system."

**Comment by jfehrle** [comment]
> > We should have a description somewhere of what dune/makefile changes you need to make when you add new code files

> > The following doesn't look right

> That's a debian / ubuntu problem, hard for us to workaround

I was thinking it could be mentioned in dune setup instructions rather than a fix.

> we already do

Ah, where?  When I search for "add" I only see "You are are not supposed to modify the `dune` files unless you are adding a new binary, library, or plugin." in `build-system.dune.md` and no relevant hits in the other md files.

> questions related to improving dune documentation / usability should be handled separately IMO

Sure, I changed this to a doc issue.

**Comment by ejgallego** [comment]
It seems to me all the issues here are solved, or not related to Coq. Please don't reopen this issue, but open new ones with a concrete documentation problem so we can proceed to fix them.
