### ISSUE TITLE
Coq Platform 8.14~2022.01 on macOS 10.13.6 

### ISSUE THREAD

**Issue by richfh** [coq/coq#15716]
Unable to run Coq Platform 8.14~2022.01 on macOS 10.13.6 using the binary installer at:
https://github.com/coq/platform/releases/tag/2022.01.0
which states:
"This installer is only compatible with macOS 10.13 or higher."

However, attempts to run coqtop, coqc, CoqIDE result in:

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Coq-Platform-8.14~2022.01.app/Contents/Resources/bin/coqtop (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Coq-Platform-8.14~2022.01.app/Contents/Resources/bin/coqtop (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by herbelin** [comment]
I just tried on MacOS 10.13.6 and I got the same error when running coqc or coqtop. When running coqide, I have another symbol not found:
```
Contents/Resources/bin/coqide
dyld: Symbol not found: ___kCFBooleanTrue
  Referenced from: /Volumes/Coq-Platform-8.14~2022.01-installer-macos-signed/Coq-Platform-8.14~2022.01.app/Contents/Resources/bin/../lib/dylib/libgdk-3.0.dylib (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Volumes/Coq-Platform-8.14~2022.01-installer-macos-signed/Coq-Platform-8.14~2022.01.app/Contents/Resources/bin/../lib/dylib/libgdk-3.0.dylib
```

**Comment by herbelin** [comment]
The correct place for this to be reported is rather [coq/platform](https://github.com/coq/platform). I don't know if it is simply that the support for 10.13 has been dropped or if something went wrong when preparing the archive. With the complexity of its dependencies, the platform is actually a work of very high technicity and your help may be required again for testing if you 're ok (assuming it is supposed to work on 10.13).

(Same failure with the 8.15 beta1 version actually)

**Comment by richfh** [comment]
I'm new to the Coq githubs, should I delete Issue #15716 and submit a new issue at coq/platform?

I'm willing to help with testing. I run 10.13.6 on one machine that cannot be updated to a later version of OS X.

**Comment by JasonGross** [comment]
I think just close this and open a new issue there, no need to delete this issue

**Comment by Zimmi48** [comment]
FWIW, Coq core members have also the power to transfer issues from one repo to another.

**Comment by Zimmi48** [comment]
Anyway this was moved to: https://github.com/coq/platform/issues/220

**Comment by JasonGross** [comment]
> FWIW, Coq core members have also the power to transfer issues from one repo to another.

Ah, good to know, I somehow missed that
