### PR TITLE
Fix #7026: ssr: applying an overloaded lemma as a view takes too long.

### LINKED ISSUE #7026: ssr: applying an overloaded lemma as a view takes too long
#### Version

Coq 8.7.2 compiled with OCaml 4.06.0
Coq 8.8+alpha compiled with OCaml 4.06.1 (coq.dev OPAM package)

#### Operating system

macOS 10.13.3 High Sierra

#### Description of the problem

The self-contained example is in [this gist](https://gist.github.com/anton-trunov/6c9fd2d821a7f8a56959dac95a0a0d30).
The code is a minimized version of the heap cancellation algorithm from "How to Make Ad Hoc Proof Automation Less Ad Hoc" by G. Gonthier, B. Ziliani, A. Nanevski and D. Dreyer (sect. 4).

```coq
Example stress 
  (h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 : heap) :
  valid (h1 :+ h2 :+ h3 :+ h4 :+ h5 :+ h6 :+ h7 :+ h8 :+ h9 :+ h10 :+ h11 :+ h12 :+ h13 :+ h14 :+ h15) ->

  h1 :+ h2 :+ h3 :+ h4 :+ h5 :+ h6 :+ h7 :+ h8 :+ h9 :+ h10 :+ h11 :+ h12 :+ h13 :+  h14 :+ h15
=
  h1 :+ h2 :+ h3 :+ h4 :+ h5 :+ h6 :+ h7 :+ h8 :+ h9 :+ h10 :+ h11 :+ h12 :+ h13 :+  h16 ->

  h15 :+ h14 = h16.
move=>D.
(* Slow -- 4 secs on my machine and hogs gigabytes of RAM
   Running time and memory consumption seem to grow exponentially with adding more variables
 *)
Time move/(cancelR D)=>/=->.

Restart.

(* If we explicitly supply H, then it's much faster -- 0.3 secs on my machine *)
move=>D H.
Time move: (cancelR D H)=>/=->.
by [].
Qed.
```

The original code from the paper was tested with Coq 8.4. This minimized example runs for about 1 second in both cases under Coq 8.4.5 and SSReflect 1.5.0.

### PR DESCRIPTION
**Pull request by ppedrot**
Ssreflect was using a very complex function performing amongst other things
refolding to check that a term was an applied inductive type. It now relies
on a simple reduction followed by term matching.

Fixes #7026.

### CODE REVIEW

**Comment by anton-trunov** [comment]
I can also confirm that this PR fixes the problem:
```
Finished transaction in 0.396 secs (0.336u,0.057s) (successful)
Finished transaction in 0.22 secs (0.212u,0.002s) (successful)
```

I also tried the same test with Coq 8.6.1 compiled with with OCaml 4.05 + ssreflect 1.6.4 and got almost the same results:
```
Finished transaction in 0.387 secs (0.318u,0.064s) (successful)
Finished transaction in 0.188 secs (0.156u,0.002s) (successful)
```

Now I'm curious about this performance difference: applying a view is twice as slow as moving the head of the goal to the context and then explicitly using it.

(CC @ejgallego: this performance degradation happened somewhere between 8.6.1 and 8.7.0)

**Comment by ejgallego** [comment]
@anton-trunov so setting up a quick bisect run script would be great to try to pinpoint the exact commit.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
> Now I'm curious about this performance difference: applying a view is twice as slow as moving the head of the goal to the context and then explicitly using it.

Give me an example please.

**Comment by anton-trunov** [comment]
In the example I provided for #7026,

```coq
move=>D /(cancelR D).
```
is two times slower compared to

```coq
move=>D H; move: (cancelR D H).
```

**Comment by Zimmi48** [comment]
> I've a problem with the milestone. I'm going to eventually merge this in master, not to backport it to 8.8 as the milestone suggests

Do you mean that you think it shouldn't be backported or that it is not your responsibility? If that's the latter, you are right. If that's the former, please put the 8.9 milestone instead.

**Comment by gares** [comment]
> it is not your responsibility?

this one

**Comment by gares** [comment]
@anton-trunov that's exactly what I say.  When you use something as  view, then Hint Views are tried, if you use the same term *not* as a view, well, Hint Views are not used.

**Comment by gares** [comment]
Maybe the thing is: a term is not a view per se. It depends how you use it, e.g.
-  `/v`: `v` is used as a view
- `(v x)`: `v` is used as a term

**Comment by anton-trunov** [comment]
>When you use something as view, then Hint Views are tried

@gares So, if I add more hints it should increase the typecheking time, right?
I added a bunch of new hints (about 30), but `Time` command reports the same time as with the few standard view hints.

Is there a way to debug this? Thank you and sorry for my late reply.

**Comment by anton-trunov** [comment]
Thank you for your response. To make the debug output more or less intelligible, I simplified the example (I hope it still makes sense):

```coq
Set Debug Ssreflect.

Example debug (h1 h2 h3 : heap) : valid (h1 :+ h2) ->
  h1 :+ h2 = h1 :+ h2 ->
  True.
move=>D/(cancelR D).   (* see debug output 1 *)
Undo.
move=>D V; move: {V}(cancelR D V).   (* see debug output 2*)
```

### debug output 1

```
Debug: SSR: ipat@run: D /(cancelR D)
Debug: SSR: exec: D
Debug: SSR:  on state: {{ to_clear:   }} goal:
  
  h1, h2, h3 : heap
  ============================
  valid (h1 :+ h2) -> h1 :+ h2 = h1 :+ h2 -> True
Debug: SSR: done: {{ to_clear:   }}
Debug: SSR: exec: /(cancelR D)
Debug: SSR:  on state: {{ to_clear:   }} goal:
  
  h1, h2, h3 : heap
  D : valid (h1 :+ h2)
  ============================
  h1 :+ h2 = h1 :+ h2 -> True
Debug: SSR: piling...
Debug: SSR: ..a term
Debug: SSR: view
Debug: SSR: interp-in: (cancelR D)
Debug:
SSR: interp-out: (cancelR
                    (f1:=union_struct (var_struct (extend_struct h1))
                           (var_struct (recurse_struct h1 (extend_struct h2))))
                    D)
Debug: SSR: interp-in: ((cancelR D) _ _ _ _ _ _)
Debug: SSR: interp-err: ((cancelR D) _ _ _ _ _ _)
Debug: SSR: interp-in: ((cancelR D) _ssr_inj_constr_in_glob_)
Debug:
SSR: interp-out: (cancelR
                    (f1:=union_struct (var_struct (extend_struct h1))
                           (var_struct (recurse_struct h1 (extend_struct h2))))
                    (f2:=union_struct (var_struct (found_struct h1 [h2]))
                           (var_struct (recurse_struct h1 (found_struct h2 []))))
                    D _view_subject_)
Debug:
SSR: view@finalized: (cancelR
                        (f1:=union_struct (var_struct (extend_struct h1))
                               (var_struct
                                  (recurse_struct h1 (extend_struct h2))))
                        (f2:=union_struct (var_struct (found_struct h1 [h2]))
                               (var_struct
                                  (recurse_struct h1 (found_struct h2 [])))) D
                        _view_subject_)
Debug: SSR: done: {{ to_clear: _view_subject_  }}
```


### debug output 2

```
Debug: SSR: globbing pattern: (cancelR D V)
Debug: SSR: ipat@run: D V
Debug: SSR: exec: D
Debug: SSR:  on state: {{ to_clear:   }} goal:
  
  h1, h2, h3 : heap
  ============================
  valid (h1 :+ h2) -> h1 :+ h2 = h1 :+ h2 -> True
Debug: SSR: done: {{ to_clear:   }}
Debug: SSR: exec: V
Debug: SSR:  on state: {{ to_clear:   }} goal:
  
  h1, h2, h3 : heap
  D : valid (h1 :+ h2)
  ============================
  h1 :+ h2 = h1 :+ h2 -> True
Debug: SSR: done: {{ to_clear:   }}
Debug: SSR: ipat@run:
Debug: SSR: interpreting: (cancelR D V)
Debug: SSR: decoded as: (cancelR D V)
Debug: SSR: typed as: (cancelR D V)
Debug:
SSR: c@gentac=(cancelR
                 (f1:=union_struct (var_struct (extend_struct h1))
                        (var_struct (recurse_struct h1 (extend_struct h2))))
                 (f2:=union_struct (var_struct (found_struct h1 [h2]))
                        (var_struct (recurse_struct h1 (found_struct h2 []))))
                 D V)
```

**Comment by gares** [comment]
Looks like we first type `cancelR D` and then try a silly `cancelR D _ _ _ _ _` and finally `cancelR D V`, so the subterm `cancelR D` is type checked 3 times, while in the other run it is typechecked once. I've to think more about it with the source code at hand. Thanks for the traces!

The traces are from 8.8beta (completely new code, so I would not be surprised of a mistake), but you say it did not happen on 8.6... so I'm a bit puzzled. In that version I think the flag was called `Set SsrDebug`. If you have it at hand, give it a run too plz. Maybe I did just misunderstood.

**Comment by gares** [comment]
Oh, and you are right, hints play no role here.

**Comment by anton-trunov** [comment]
>but you say it did not happen on 8.6... so I'm a bit puzzled.

Let me clarify the situation a bit. Before applying the current PR, I couldn't even compile some of the examples because Coq started hogging gigabytes of memory, it was just spinning and spinning for minutes, but Coq 8.6.1 does not have this problem (I'll try to bisect and figure out when exactly it happened)

After this PR has been applied I can compile the example, but I noticed that applying an overloaded lemma as a view takes approximately _twice_ as much time as moving the top assumption to the context and then explicitly providing the former top assumption as an argument to the overloaded lemma.
It works the same on 8.6.1 and 8.8beta.

I can open a separate issue for this if you think it's worth it.

Nevertheless, I ran the last example on Coq 8.6.1 & coq-mathcomp-ssreflect.dev package installed via OPAM. It yielded the following results:

### debug output 1

```
Debug: SSR: interpreting: _top_assumption_
Debug: SSR:  in ist: $arg:pair $clauses:pair
Debug: SSR: decoded as: _top_assumption_
Debug: SSR: typed as: _top_assumption_
```

### debug output 2

```
Debug: SSR: globbing pattern: (cancelR D V)
Debug: SSR: interpreting: (cancelR D V)
Debug: SSR:  in ist: $arg:pair $clauses:pair
Debug: SSR: decoded as: (cancelR D V)
Debug: SSR: typed as: (cancelR D V)
Error:
 SSR: c@gentac=(cancelR
                  (f1:=union_struct (var_struct (extend_struct h1))
                         (var_struct (recurse_struct h1 (extend_struct h2))))
                  (f2:=union_struct (var_struct (found_struct h1 [h2]))
                         (var_struct (recurse_struct h1 (found_struct h2 []))))
                  D V)
```

Here, despite the error, the overloaded lemma works.

**Comment by gares** [comment]
I think ti is worth to open a separated issue with the bisect info. IMO it will be unrelated to ssr, but also very interesting. See below.

Wrt your log, unfortunately the old debugging code is not printing all attempts view application do, so it is not going to help. I guess the point is that we do one more type checking in that case and your term (for reasons that I don't know) takes quite some time to typecheck. The potential bug/optimization here is not to run the extra type checking (if possible) but I've to think more about it. If the issue above is understood the extra type checking may even become unnoticeable.

**Comment by anton-trunov** [comment]
@gares I opened a new issue #7133 as you suggested.

**Comment by anton-trunov** [comment]
>so setting up a quick bisect run script would be great to try to pinpoint the exact commit.

@ejgallego I tried to bisect, but ran into ssreflect plugin compilation issues. Basically, all I was able to learn is that 25462adda (it's almost V8.7.0) is *bad* and c64a28ee5 is *good* (it's a bit past V8.6.1). But for the commits in the middle I can't compile the ssreflect plugin. It gives a variety of compilation errors for `ssreflect.ml4`, e.g.
```
File "_none_", line 1: Error: Unbound module Constrarg Hint: Did you mean Constant, Constrmap or Constr?
```
or
```
File "_none_", line 1: Error: Unbound module Tactic Hint: Did you mean Tactics?
```

It would be great if someone could give me a hand and show how to compile ssreflect with e.g. 129faf2db.
Another approach would be to emulate ssr's view mechanism with standard Coq tactics (if it's possible at all).

(CC @gares)

**Comment by anton-trunov** [comment]
I just discovered that if I do
```
Timeout 1 move=>D/(cancelR D).
```
for the running example, then Coq 8.7.2 (i.e. Coq without this fix) spins for about 1 second but then (after the interruption) produces **correct** output! `Timeout 2 ...`, etc. also works.

If I remove `Timeout` Coq spins indefinitely. 

In my opinion this might be an indicator of a bit more serious issue.

**Comment by ejgallego** [comment]
> @ejgallego I tried to bisect, but ran into ssreflect plugin compilation issues. Basically, all I was able to learn is that 25462ad (it's almost V8.7.0) is bad and c64a28e is good (it's a bit past V8.6.1). But for the commits in the middle I can't compile the ssreflect plugin. It gives a variety of compilation errors for ssreflect.ml4, e.g.

Yeah that's tricky and one of the reasons we should move most plugins in-tree as advocated by some development methodologies.

However, if Travis was successful on some particular commit, you can actually determine from the Travis build log what is the correct ssreflect commit you need in order to build. It is even possible to automate this but I guess manually doing that would be faster.

**Comment by anton-trunov** [comment]
Following your advice, I narrowed it down to about 100 commits: 7a51d6a94 (good) .. 835be3a05 (bad).

It looks like the bug was introduced in #379 & math-comp/math-comp#119. #379 has 104 commits and I couldn't compile ssreflect with the commits in the middle of #379.

**Comment by ejgallego** [comment]
@anton-trunov thanks, your work is very useful to confirm @ppedrot 's guess in #7133 . Indeed, it is not worth it to continue the rebase, it could be done but it'd be a lot of work as the API changed mid-merge, etc...

So I guess #7133 should be renamed to "EConstr-related performance regression on `move/view`" or something like that.
