### PR TITLE
Let Arguments support anonymous implicit arguments

### LINKED ISSUE #4696: Arguments does not set implicit arguments on anonymous variables
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#4696
From: @ppedrot
Reported version: 8.5
CC:   @silene, @herbelin, @maximedenes

### LINKED ISSUE #5173: "Error: Argument _ cannot be declared implicit." is extremely underinformative
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5173
From: @JasonGross
Reported version: 8.6
CC:   coq-bugs-redist@lists.gforge.inria.fr

### LINKED ISSUE #9098: please explain why arguments of S cannot be made implicit
#### Version

8.8.2

#### Operating system

Arch Linux, up to date as of one week

#### Description of the problem

~~~~~coq
Arguments S {_}.
(* Error: Argument _ cannot be declared implicit. *)
~~~~~

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** enhancement

Depends on #10202. 

As noticed by @ejgallego, this fixes #5173, fixes #4696, fixes #9098.

It is possible to declare an anonymous implicit argument using `{ _ }` in the declaration of the object. Type classes also set some anonymous arguments implicit.

By consistency, this PR also let `Arguments` set an anonymous implicit argument as in:
```
Arguments id {A} {_}.
Check id (arg_2:=true).
Check id : bool.
```

Note: the anonymous argument can be made explicit using `arg_XX` where `XX` is the index of the argument among all arguments. I'm not a big fan of this syntax but this PR does not prevent to use it on the newly declared anonymous implicit arguments.

- [X] Added / updated test-suite
- [x] Corresponding documentation was added / updated (this is minor but maybe a word should be said)
- [x] Entry added in the changelog (this is minor but maybe a word should be said)

### CODE REVIEW

**Comment by Zimmi48** [comment]
> Note: the anonymous argument can be made explicit using `arg_XX` where `XX` is the index of the argument among all arguments. I'm not a big fan of this syntax but this PR does not prevent to use it on the newly declared anonymous implicit arguments.

AFAIK this is undocumented syntax. Can we have another PR removing it to check how much breakage that would occur?

**Comment by herbelin** [comment]
> > Note: the anonymous argument can be made explicit using `arg_XX` where `XX` is the index of the argument among all arguments. I'm not a big fan of this syntax but this PR does not prevent to use it on the newly declared anonymous implicit arguments.
> 
> AFAIK this is undocumented syntax. Can we have another PR removing it to check how much breakage that would occur?

Yes, now that `About` uses `Arguments` to report about implicit arguments, that may be worth trying to remove the `arg_XX` trick. For the record, the names `arg_XX` were otherwise reported by `About` as in the example:
```
Axiom f : forall {_:nat}, nat.
About f. (* formerly printing "Argument arg_1 is implicit and maximally inserted" *)
```
See also [#6785](https://github.com/coq/coq/issues/6785#issuecomment-366809090) for related issues with `arg_XX`.

See also #11099 for a syntax alternative to `arg_XX`.

**Comment by herbelin** [comment]
@Zimmi48:

> Yes, now that `About` uses `Arguments` to report about implicit arguments, that may be worth trying to remove the arg_XX trick. For the record, the names arg_XX were otherwise reported by `About` as in the example:

Actually, `Print Implicit f` is still showing `arg_n` names.
```
Axiom f : forall {_:nat}, nat.
Print Implicit f.
(* Argument arg_1 is implicit and maximally inserted *)
```

@skyskimmer (and all): Personally, I use `About` and `Print Implicit` is probably a bit obsolete now, but it seems to me that it might make sense that `Print Implicit` uses `Arguments` too (and even that it generalizes to a `Print Arguments f` command?). Any opinion?

**Review by ejgallego — APPROVED** [review]
It seems the limitation to forbid renaming of anonymous implicit arguments was introduced in 39fd2b160dbbd6411dd05f52984f198338de300a , the implementation has changed quite a lot since then, the current patch looks good to me so I don't expect any problems.

I wonder about the changelog entry tho, given recent comments in other PRs maybe it would be worth adding a very small note? Indeed it seems possible to me that some users could find this behavior useful and are avoiding this due to the current limitation [3 issues fixed could corroborate this]

Will merge soon if no more comments.

**Comment by ejgallego** [comment]
> Will merge soon if no more comments.

And after a changelog is added [unless @herbelin thinks it's not needed]

**Comment by herbelin** [comment]
@ejgallego: I pushed a change log (mentioning the wishes it fixes) and modified the documentation (it was actually assuming that only `@ident` and not `@name` could be made implicit).

The question of the `arg_X` syntax is still open, but we will certainly have to come back to it at some time of the other implicit arguments PR. Thanks a lot.

**Comment by herbelin** [comment]
@Zimmi48 : I have a compilation error (*) on ``:cmd:`Arguments` `` in the change log, but there is a `cmd:: Arguments` in the manual. I saw that you wrote ``cmd:`Arguments <Arguments (implicits)>` `` in the change log for #11368. Is it what I should do too?

(*) `<rst_prolog>:11:coq:cmd reference target not found: Arguments`

**Comment by Zimmi48** [comment]
> @Zimmi48 : I have a compilation error (*) on `` :cmd:`Arguments` `` in the change log, but there is a `cmd:: Arguments` in the manual. I saw that you wrote `` cmd:`Arguments <Arguments (implicits)>` `` in the change log for #11368. Is it what I should do too?
> 
> (*) `<rst_prolog>:11:coq:cmd reference target not found: Arguments`

Sorry for having missed that. Yes, this is because the `Arguments` command is defined multiple times. So each instance have its `:name:` option which further specify the specific `Arguments` command with some parenthesis. Cf. the command index for the full list: https://coq.github.io/doc/master/refman/coq-cmdindex.html#cap-a

**Review by Zimmi48 — APPROVED** [review]

**Comment by ejgallego** [comment]
Ready to go.
