### PR TITLE
Remove unwanted "(optional)"

### PR DESCRIPTION
**Pull request by jfehrle**
Fix the merge error introduced in #16142.  See [here](https://github.com/coq/coq/pull/16142#discussion_r995835567).

What are the consequences of having "(optional)"?  Should this PR be included with the backport of #16142 to 8.16.1?  Will it be a problem for users of the latest Coq Platform beta?

Attn: @ejgallego

### CODE REVIEW

**Comment by Alizter** [comment]
If you don't have the library dependencies for CoqIDE present and you try to build it with Dune it will fail silently. This would mean that rather than reporting a missing dep, and install might just do nothing silently.

**Review by Alizter — APPROVED** [review]

**Comment by ppedrot** [comment]
The original PR is not part of 8.16.1 yet, I'll just tweak it on my backport branch.

**Comment by Alizter** [comment]
It looks like now that the CI is not failing silently building CoqIDE that CoqIDE never built on Windows :/

**Comment by ppedrot** [comment]
Hmm, for some reason the 8.16 branch already has the `(optional)` modifier set, so it is faulty, somehow. Not sure what this entails for the end-user.

**Comment by Alizter** [comment]
Hmm ok looks like we removed the optional in 8.17 only. No need to back port this I guess.

**Comment by Alizter** [comment]
However this does mean @jfehrle's https://github.com/coq/coq/pull/16142 doesn't work in the current CI for 8.17. Since undoing the accidental `(optional)` fails the CI.

**Comment by jfehrle** [comment]
Maybe not related:  The Windows installer link on the [Coq Platform](https://github.com/coq/platform/releases/tag/2022.09.0) gets a "page not found" error, as does the Mac installer link.  @MSoegtropIMC, any thoughts?

**Comment by jfehrle** [comment]
The failure message for the Windows CI is on a line that I didn't change for #16142 in a file that already existed.  That's odd.  OTOH I've noticed lots of Windows build failures over the last months, which I've never bothered to investigate, assuming that they were random failures.  Perhaps this is a random failure?

```
# File "ide/coqide/coqide_WIN32.ml.in", line 51, characters 37-68:
# Error: Unbound value Glib.Io.channel_of_descr_socket
```

**Comment by jfehrle** [comment]
@coqbot run full CI

**Comment by Zimmi48** [comment]
> The failure message for the Windows CI is on a line that I didn't change for #16142 in a file that already existed. That's odd. OTOH I've noticed lots of Windows build failures over the last months, which I've never bothered to investigate, assuming that they were random failures. Perhaps this is a random failure?
> 
> ```
> # File "ide/coqide/coqide_WIN32.ml.in", line 51, characters 37-68:
> # Error: Unbound value Glib.Io.channel_of_descr_socket
> ```

That doesn't look random to me.

**Comment by Zimmi48** [comment]
> Maybe not related: The Windows installer link on the [Coq Platform](https://github.com/coq/platform/releases/tag/2022.09.0) webpage gets a "page not found" error, as does the Mac installer link. @MSoegtropIMC, any thoughts?

Fixed. This was an issue with the link changing when publishing the release. So this section should be completed carefully next time.

> When I install this Windows binary on [this page](https://github.com/coq/platform/releases/tag/2022.09.0), there is a CoqIDE but it doesn't have my fix. Maybe I need to go through the platform script?
> 
> image

No, it is supposed to be exactly the same that you get when going through the installer or the platform scripts, so it is weird that it doesn't have your fix.

**Comment by jfehrle** [comment]
> PS: I don't think that requesting a full CI was too useful in the case of this PR.

I wanted to rerun the windows job in case it was random (even if not a great hypothesis :-().  If it isn't already there, it would be nice to have a way to tell coqbot which jobs to run.  Also an option to rerun only the failing jobs of the full option (maybe that's a good default?).    (If you do a full and then you do a short by mistake, currently IIUC you have to do another full.)  I've not paid complete attention to the full vs light discussion.

What would it cost to get access to the same number of minutes that we had before?  Do we have other ideas on how to reduce our usage?  Maybe it would be helpful to get some stats on how long various jobs take to define subsets.    Is the unit minutes per core or minutes per processor?  If it's the latter, maybe we could do better by bumping up the number of jobs.

(Feel free to continue this sidelight elsewhere, eg email.)

**Comment by jfehrle** [comment]
Also I see the same failure on Windows for #16659, which is doc-only, so probably has nothing to do with teh `(optional)`.  Maybe the library version changed?

**Comment by Zimmi48** [comment]
Yes. The explanation is there: https://coq.zulipchat.com/#narrow/stream/250632-Coq-Platform-devs-.26-users/topic/Building.20from.20sources.20fails.20on.20Windows/near/304283880

A fix is being tested in coq/platform#304 and should hopefully be merged soon.

**Comment by Zimmi48** [comment]
> I wanted to rerun the windows job in case it was random (even if not a great hypothesis :-(). If it isn't already there, it would be nice to have a way to tell coqbot which jobs to run.

The `run full CI` command is to run a full GitLab CI pipeline and the `run CI` (if there is no `request: full CI` label set) or the more explicit `run light CI` commands are to run a light CI. But most importantly, these commands are not for re-running any job, they are for triggering a new GitLab pipeline (new merge commit with master, etc.). Something to note is that the Windows and macOS jobs are not part of the GitLab pipeline, so they are completely independent of what coqbot manages.

There already is (and was for a long time) a feature for retrying failed jobs. Just click on "Details" then on "Re-run".

>What would it cost to get access to the same number of minutes that we had before?

About 3000€ / months if we wanted to continue using the GitLab shared runners exactly as before. But we are actually replacing these by custom runners and the cost should be much reduced. If you want more answers / to contribute to the discussion around CI, please head over to Zulip (Coq devs & plugin devs stream). There are already a lot of answers there. That being said, I think we are doing OK.

**Comment by Zimmi48** [comment]
@MSoegtropIMC This is because I fixed them. See what I wrote above:

>Fixed. This was an issue with the link changing when publishing the release. So this section should be completed carefully next time.

**Comment by jfehrle** [comment]
> There already is (and was for a long time) a feature for retrying failed jobs. Just click on "Details" then on "Re-run".

I think that's helpful only for addressing random failures when the developer hasn't pushed new code.  Suppose the PR has a failure only in ci_fiat_crypto and you make a fix to address that.  It would be helpful to be able to rerun only that job and its prerequisites--or just the jobs that failed in the last full run, or a specific named group of jobs and their prerequisites.  Of course, you would later run a full build before the merge.

**Comment by jfehrle** [comment]
> If you want more answers / to contribute to the discussion around CI, please head over to Zulip (Coq devs & plugin devs stream).

I couldn't find it.  There are a vast number of messages there.  Is there a way to search for that discussion or do a text search?

**Comment by Zimmi48** [comment]
> Suppose the PR has a failure only in ci_fiat_crypto and you make a fix to address that. It would be helpful to be able to rerun only that job and its prerequisites--or just the jobs that failed in the last full run, or a specific named group of jobs and their prerequisites. Of course, you would later run a full build before the merge.

OK. Yes, it would make sense to introduce a way of requesting only a specific job and its dependencies. It would require some design at the level of the GitLab CI configuration besides the support to add to @coqbot, and I'm too tired right now to think of good ways of doing this. But feel free to propose this on Zulip to get more feedback / design brainstorming, or to open an issue on the bot repo to record the idea until we come back to it.

>I couldn't find it. There are a vast number of messages there. Is there a way to search for that discussion or do a text search?

The discussion started here: [CI pipeline minutes running out](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/CI.20pipeline.20minutes.20running.20out)

Then there were some spin-offs to have a more structured discussion:
- [Upcoming GitLab CI storage limits](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Upcoming.20GitLab.20CI.20storage.20limits)
- [Actions taken on CI because of minutes running out](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Actions.20taken.20on.20CI.20because.20of.20minutes.20running.20out)
- [Runner failures](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Runner.20failures)
- [Runner failures on docker-machine runner](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Runner.20failures.20on.20docker-machine.20runner)
- [Runner failures on ci-coq-02-runner-*](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Runner.20failures.20on.20ci-coq-02-runner-*)

**Comment by Alizter** [comment]
@jfehrle Could you rebase so we can get a fresh CI?

**Comment by jfehrle** [comment]
Done.

**Comment by Alizter** [comment]
@coqbot merge now
