### PR TITLE
Fixes #14256, extraction: unsafeCoerce moved to different module in GHC >= 9.0.0

### LINKED ISSUE #14256: Haskell extraction is broken for ghc 9.0
```coq
Require Import Coq.extraction.ExtrHaskellBasic.
Extraction Language Haskell.
Definition foo (t : { T : Type & T }) := projT2 t.
Definition bar := foo (existT _ (nat:Type) 0).
Recursive Extraction bar.
(*
{-# OPTIONS_GHC -cpp -XMagicHash #-}
{- For Hugs, use the option -F"cpp -P -traditional" -}

module Main where

import qualified Prelude

#ifdef __GLASGOW_HASKELL__
import qualified GHC.Base
import qualified GHC.Prim
#else
-- HUGS
import qualified IOExts
#endif

#ifdef __GLASGOW_HASKELL__
unsafeCoerce :: a -> b
unsafeCoerce = GHC.Base.unsafeCoerce#
#else
-- HUGS
unsafeCoerce :: a -> b
unsafeCoerce = IOExts.unsafeCoerce
#endif

#ifdef __GLASGOW_HASKELL__
type Any = GHC.Prim.Any
#else
-- HUGS
type Any = ()
#endif

__ :: any
__ = Prelude.error "Logical or arity value used"

data Nat =
   O
 | S Nat

data SigT a p =
   ExistT a p

projT2 :: (SigT a1 a2) -> a2
projT2 x =
  case x of {
   ExistT _ h -> h}

foo :: (SigT () Any) -> Any
foo t =
  projT2 t

bar :: Nat
bar =
  unsafeCoerce foo (ExistT __ (unsafeCoerce O))

*)
```
This code does not compile with ghc 9.0.1, failing with 
```
Error:     Not in scope: ‘GHC.Base.unsafeCoerce#’
    Perhaps you meant ‘GHC.Base.unsafeChr’ (imported from GHC.Base)
    Module ‘GHC.Base’ does not export ‘unsafeCoerce#’.
   |
22 | unsafeCoerce = GHC.Base.unsafeCoerce#
   |                ^^^^^^^^^^^^^^^^^^^^^^
```

According to https://github.com/haskell/primitive/issues/258, we should be using `GHC.Exts.unsafeCoerce#`, but the diff at https://gitlab.haskell.org/ghc/ghc/commit/74ad75e87317196c600dfabc61aee1b87d95c214 suggests this is not backwards compatible.

Also, it seems extraction is already broken on earlier versions of Haskell, as I get
```
/tmp/foo.hs:26:12: error:
    Not in scope: type constructor or class ‘GHC.Prim.Any’
    Perhaps you meant ‘GHC.Prim.Int#’ (imported from GHC.Prim)
    Module ‘GHC.Prim’ does not export ‘Any’.
   |
26 | type Any = GHC.Prim.Any
   |            ^^^^^^^^^^^^
```
with 8.6.5.

cc, uh, @zeldovich ?  (I'm not sure who knows about Hakell extraction)

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** enhancement

Fixes / closes #14256. This adds unsafeCoerce compatibility with GHC >= 9.0.0.

- [ ] Entry added in the changelog

### CODE REVIEW

**Comment by herbelin** [comment]
Redundant, see #14345.

File: plugins/extraction/haskell.ml [hunk 1]
```diff
@@ -64,13 +64,18 @@ let preamble mod_name comment used_modules usf =
   ++
   (if not usf.magic then mt ()
    else
-     str "#ifdef __GLASGOW_HASKELL__" ++ fnl () ++
+     str "#ifdef __GLASGOW_HASKELL__ < 900" ++ fnl () ++
```
Comment (JasonGross) [inline plugins/extraction/haskell.ml:67]: Does this actually work?  It doesn't seem to be valid in C/C++ according to https://en.cppreference.com/w/cpp/preprocessor/conditional, but I can't find the Haskell documentation

Comment (pi8027) [reply plugins/extraction/haskell.ml:67]: In the `Example` on that page, I found the following line. So I guess it is fine.
```
#if !defined(DCBA) && (ABCD < 2*4-3)
```

Comment (herbelin) [reply plugins/extraction/haskell.ml:67]: For the syntax, I trusted https://guide.aelve.com/haskell/cpp-vww0qd72.

Comment (JasonGross) [reply plugins/extraction/haskell.ml:67]: If we go with this PR, please test this (or I'll try to test it in the not too distant future) before merging

Comment (herbelin) [reply plugins/extraction/haskell.ml:67]: I tested with ghc 8.4.1 (using `ghc --cpp`) and couldn't get the `#` of `unsafeCoerce#` being parsed (was I missing an option).

In any case, based on @pi8027's comment [here](https://github.com/coq/coq/issues/14256#issuecomment-847703462), I tried to use instead `Unsafe.Coerce.unsafeCoerce` which seems to compile well with ghc 8.4.1, and presumably for ghc >= 9, without having to worry about the exact version of ghc. So, I updated the PR.

(Incidentally, the `#ifdef` should have been a `#if` above, but that's not necessary anymore.)

Comment (pi8027) [reply plugins/extraction/haskell.ml:67]: > I tested with ghc 8.4.1 (using `ghc --cpp`) and couldn't get the `#` of `unsafeCoerce#` being parsed (was I missing an option).

`{-# OPTIONS_GHC -cpp -XMagicHash #-}` is needed for that.
